### ISSUE TITLE
请问demo图片中的用的皮肤和字体是什么？

### ISSUE THREAD

**Issue by laubonghaudoi** [chromezh/rime-kunyomi#1]
![image](https://user-images.githubusercontent.com/11172180/57260099-13c8db80-7017-11e9-83f2-37f8bbd8bf36.png)
这个字体好象是明朝花园体？请问怎样才能让小狼毫显示这个字体？另外这个配色主题叫什么名字呢？在哪里可以下载？

**Comment by sgalal** [comment]
是 Windows 10 自带的 Yu Mincho 字体。

在 `weasel.custom.yaml` 中添加：

```yaml
patch:
  "style/color_scheme": brisk
  "style/font_face": "Yu Mincho"
  "style/horizontal": true
  "style/layout/border": 1
  "style/layout/corner_radius": 0
  "style/layout/hilite_padding": 10
  "style/layout/hilite_spacing": 10
  "style/layout/margin_x": 11
  "style/layout/margin_y": 11
  "style/layout/round_corner": 0
  "style/layout/spacing": 20
```
